version: 2

sources:
 - name: raw
   database: gen-lang-client-0099843416
   schema: gz_raw_data
   description: "Raw datasets ingested from source systems"
   tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: "Google Ads (AdWords) daily campaign performance raw data."
        columns:
          - name: date_date
            description: "Date of the metrics."
            tests: [not_null]
          - name: paid_source
            description: "Source label (should be 'adwords' in this raw table)."
          - name: campaign_key
            description: "Campaign unique identifier."
            tests: [not_null]
          - name: campaign_name
            description: "Campaign name."
          - name: ads_cost
            description: "Ad spend / cost."
          - name: impression
            description: "Number of impressions."
          - name: click
            description: "Number of clicks."

      - name: bing
        identifier: raw_gz_bing
        description: "Bing Ads daily campaign performance raw data."
        columns:
          - name: date_date
            description: "Date of the metrics."
            tests: [not_null]
          - name: paid_source
            description: "Source label (should be 'bing' in this raw table)."
          - name: campaign_key
            description: "Campaign unique identifier."
            tests: [not_null]
          - name: campaign_name
            description: "Campaign name."
          - name: ads_cost
            description: "Ad spend / cost."
          - name: impression
            description: "Number of impressions."
          - name: click
            description: "Number of clicks."

      - name: criteo
        identifier: raw_gz_criteo
        description: "Criteo daily campaign performance raw data."
        columns:
          - name: date_date
            description: "Date of the metrics."
            tests: [not_null]
          - name: paid_source
            description: "Source label (should be 'criteo' in this raw table)."
          - name: campaign_key
            description: "Campaign unique identifier."
            tests: [not_null]
          - name: campaign_name
            description: "Campaign name."
          - name: ads_cost
            description: "Ad spend / cost."
          - name: impression
            description: "Number of impressions."
          - name: click
            description: "Number of clicks."

      - name: facebook
        identifier: raw_gz_facebook
        description: "Facebook Ads daily campaign performance raw data."
        columns:
          - name: date_date
            description: "Date of the metrics."
            tests: [not_null]
          - name: paid_source
            description: "Source label (should be 'facebook' in this raw table)."
          - name: campaign_key
            description: "Campaign unique identifier."
            tests: [not_null]
          - name: campaign_name
            description: "Campaign name."
          - name: ads_cost
            description: "Ad spend / cost."
          - name: impression
            description: "Number of impressions."
          - name: click
            description: "Number of clicks."

      - name: sales
        identifier: raw_gz_sales
        description: "Raw sales transactions data"
        columns:
          - name: date_date
            description: "Date when the sales transaction occurred"

          - name: orders_id
            description: "Unique identifier of the order"

          - name: pdt_id
            description: "Identifier of the product sold"

          - name: revenue
            description: "Revenue generated by the order line"

          - name: quantity
            description: "Number of units sold in the order line"

      - name: product
        identifier: raw_gz_product
        description: "Raw product master data"
        columns:
          - name: products_id
            description: "Unique identifier of the product"
            tests:
             - not_null
             - unique

      - name: purchSE_PRICE
        description: "Purchase price in raw source (needs cleaning/casting)"

      - name: ship
        identifier: raw_gz_ship
        description: "Raw shipping information per order"
        columns:
          - name: orders_id
            description: "Unique identifier of the order"
            tests:
             - not_null
             - unique
            
          - name: shipping_fee
            description: "Shipping fee charged for the order"

          - name: shipping_fee_1
            description: "Duplicate shipping fee field from alternative source"

          - name: logCost
            description: "Raw logistics cost (needs cleaning/casting)"

          - name: ship_cost
            description: "Raw shipping cost as string (needs cleaning/casting)"

models:
  - name: stg_raw_sales
    columns:
      - name: sales_pk
        description: "Surrogate primary key for sales lines (orders_id + product id)"
        tests:
          - not_null
          - unique
  - name: int_campaigns_day
    description: "Daily aggregated campaign performance"
    columns:
      - name: date_date
        tests:
          - not_null

  - name: finance_campaigns_day
    description: "Finance mart combining campaigns and operational metrics"
    columns:
      - name: date
        tests:
          - not_null





